GET http://localhost:1337/api/events?past=true
Accept: application/json

###
POST http://localhost:1337/api/events
Content-Type: application/json
Accept: application/json

{
    "date": "2018-03-21T00:00:00",
    "location": "Linz"
}

###
POST http://localhost:1337/api/events/5b1cc47c9e549d5324d14794/registrations
Content-Type: application/json
Accept: application/json

{
    "participant": 
    {
        "givenName": "John",
        "familyName": "Doe"
    }
}

###
GET http://localhost:1337/api/events/5b1cc47c9e549d5324d14794/registrations
Accept: application/json

###
POST http://localhost:1337/api/participants/5b1cdae187dae00eb4eebae3/checkin/5b1cc47c9e549d5324d14794
Content-Type: application/json
Accept: application/json

