@host=http://swagger-workshop.westeurope.azurecontainer.io
#@host=http://localhost:1337
@generator-host=http://localhost:8082

###
GET {{host}}/api/events?past=true
Accept: application/json

###
POST {{host}}/api/events
Content-Type: application/json
Accept: application/json

{
    "date": "2018-03-21T00:00:00",
    "location": "Linz"
}

###
POST {{host}}/api/events/5b1cc47c9e549d5324d14794/registrations
Content-Type: application/json
Accept: application/json

{
    "participant": 
    {
        "givenName": "John",
        "familyName": "Doe"
    }
}

###
GET {{host}}/api/events/5b1cc47c9e549d5324d14794/registrations
Accept: application/json

###
POST {{host}}/api/participants/5b1cdae187dae00eb4eebae3/checkin/5b1cc47c9e549d5324d14794
Content-Type: application/json
Accept: application/json

###
GET {{generator-host}}/api/gen/clients/
Accept: application/json

###
# See https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache
# for corresponding template
GET {{generator-host}}/api/gen/clients/typescript-node
Accept: application/json

###
POST {{generator-host}}/api/gen/clients/typescript-node
Content-Type: application/json

{
  "spec": {},
  "options": {
      "supportsES6": true
  },
  "swaggerUrl": "https://raw.githack.com/rstropek/node-mongo-sample/master/api2.json",
  "authorizationValue": {},
  "securityDefinition": {}
}